version: "3.9"

services:
  web:
    image: tarastroshchuk/cloud-labs-web:latest
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000" 
    command: python run.py
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}"

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --interval 60
      --cleanup
      --include-stopped
      --revive-stopped
